### ISSUE TITLE
Dialog for message signing

### ISSUE THREAD

**Issue by naps62** [iron-wallet/iron#132]
The current behaviour is nice for testing & prototyping, but there are also many scenarios in development where having a popup is useful:
* debug transactions before they're signed
* configure gas and other parameters
* override erc20 approval amounts

not to mention this is a must-have for any future secure version of the wallet

For now, a simple approach: for any transaction / message, just show a small popup window with the raw data (hex, or whatever is easier for now), and confirm/reject buttons. Then we can iterate from there

The window should only show if people opt-in to a setting that we can expose

**Comment by naps62** [comment]
Update here: transaction confirmation is already live (although not styled, see #186 ). transaction signing is still missing

since it should be very similar work, I'm tagging this as a good first issue now

**Comment by miguelrdp** [comment]
Hi can we take this issue (me and @0xdorifto) ?

**Comment by naps62** [comment]
Hi
I believe so. Though I'll need to double check because I could've sworn this was already done

I'll check in a few hours. But even if it's done, there's lots of work to improve this popups (that should be plainly obvious just by looking at them)

**Comment by 0xdorifto** [comment]
Since this is already done we are going to move on to other issues.
