### ISSUE TITLE
Remove sqlite. Probably in favor of bincode

### ISSUE THREAD

**Issue by naps62** [iron-wallet/iron#135]
As said in #134 , sqlite cannot handle integers larger than 64-bits

the short term solution was to store strings instead, and doing all the math in Rust. which means we need to read -> calculate -> write, meaning two separate queries, which is not only ugly, but not safe in concurrent updates (which we don't have right now, but it's still unconfortable tech debt to have)

I'm now thinking of keeping it simple and using something like [`bincode`](https://docs.rs/bincode/latest/bincode/) to persist all data.

Most likely: keep one bincode file per chain / address, which makes it easier to read/write individual accounts, and also enables some form of parallelization

**Comment by gabrielpoca** [comment]
Btw, if you're going to consider building this for mobile, I'm not sure about bincode, but sqlite is supported by all platforms if I'm not mistaken.

**Comment by naps62** [comment]
bincode is just Rust serialization/deserialization code. it's fully platform agnostic. all I need then is some way to persist that to files

**Comment by gabrielpoca** [comment]
We'll find out then 😁

**Comment by naps62** [comment]
After medidating on this subject, I decided to stick with sqlite for now. mostly due to the pure confusion that is the embedded db ecossystem in Rust (too many options, none of them seem much better than the next. and ultimately queries would become more complicated since none of them are SQL
