### ISSUE TITLE
Detailed view of transactions

### ISSUE THREAD

**Issue by pvgo80** [iron-wallet/iron#139]
A simple view of input data, events and output of a tx. Example:

![image](https://user-images.githubusercontent.com/116551579/233681047-52e18006-9783-426f-a4b4-646f7a6b7a69.png)

Related to #97, using an ABI if possible.

**Comment by naps62** [comment]
wait. is this something you're working on already? looks awesome

**Comment by pvgo80** [comment]
There's a couple of issues:

- Too much work on the front-end -- from what I grasped of the project structure, the idea was to leverage Rust to parse and handle any interaction with the provider (hit a wall with this approach).
- Finding the ABI: (front-end) tx -> find the contract -> get the deployed code -> (back-end) iterate over each foundry compiled project -> match -> (front-end) decode everything. Although it's async, and once matched it keeps the contract in session, there's probably a clever way to do this.

And the quality is pretty meh, it probably contains some anti patterns. Since there's no rush, a more careful approach will better serve the project in the future.

**Comment by naps62** [comment]
this was done a couple of releases ago
