### ISSUE TITLE
Add dialog windows

### ISSUE THREAD

**Issue by naps62** [iron-wallet/iron#153]
This issue is being created as a dependency of #132 

Add support for creating dialog windows, to later be used for:
- transaction review (similar to metamask)
- transaction signing
- potential other features

I'm currently assuming we prefer dialog windows instead of a modal in the existing view, for a couple of reasons:
- it's more in line with the expectations of a desktop app
- allows us to close the main UI but still get these one-off interactions when needed

**Comment by naps62** [comment]
@gabrielpoca do you agree with this?

**Comment by gabrielpoca** [comment]
yes 👍
