### ISSUE TITLE
Multiple accounts

### ISSUE THREAD

**Issue by naps62** [iron-wallet/iron#154]
We want the ability to connect multiple mnemonics.

Roughly, here's what I'm thinking:

- [ ] Change `pub wallet: Wallet` to `pub wallets: Vec<Wallet>`
- [ ] the Wallet settings page becomes similar to the Network, in that we can create multiple objects and configure each one individually
- [ ] add a `wallet.count` field to indicate how many addresses we want to derive from it
- [ ] add a `wallet.alias` to allows us to give a friendlier name to each of them

no encryption will be handled here, but my future plan for that would be:
- change `Vec<Wallet>` to Vec<Box<impl Wallet>>` so that many types of Wallets can be implemented
- create a `KeystoreWallet` that reads from a json keystore file (probably the most trivial encrypted wallet we can start with)

**Comment by gabrielpoca** [comment]
What do you think about integrating a higher-level abstraction? I was thinking of something like a profile that you have in chrome, for instance?

**Comment by naps62** [comment]
I think something like that makes sense, but would definitely come later
I'd rather build these things bottom-up, because if we try to do right now a high-level abstraction, it's more likely it'll be the wrong one, or be implemented in a way that hurts us later

**Comment by gabrielpoca** [comment]
Ok, in this case I was thinking something like Profile has Wallet. You had multiple profiles, and the profile only had the property `alias` for now. But let's go 👍
