### ISSUE TITLE
Transaction review design

### ISSUE THREAD

**Issue by naps62** [iron-wallet/iron#186]
The current dialog for a transaction review is pretty much a placeholder.
we need to, at the very least, display the info properly, in the same Material style

![image](https://github.com/iron-wallet/iron/assets/283819/3af4d5a1-d5b6-4f32-89f9-03d2b0cc9dbf)

**Comment by fernanda-freitas** [comment]
Hey @naps62, I'd like to work on this. Can you assign this issue to me?

**Comment by naps62** [comment]
Already improved in #212 . Still in need of big improvements, but I belive that'll come with the implementation of features such as
