### ISSUE TITLE
Any plan to support firefox?

### ISSUE THREAD

**Issue by xphoniex** [iron-wallet/iron#228]
I can't load the extension in firefox because manifest seems to have something ff can't support (something about `background`) and looking at the code, seems like you're using APIs and functionalities only provided by chrome. 

Is this subject to change in the short term?

**Comment by naps62** [comment]
hi @xphoniex 
it's something I've been procrastinating, but want to get solved now that more people are starting to use this.

The extension itself doesn't do anything browser-specific (and a lot of the logic is based off of MetaMask), so I imagine it's mostly about making the manifest and other infrastructure compatible

@gabrielpoca will you have time to look into this this week, or shall I?

**Comment by naps62** [comment]
> seems like you're using APIs and functionalities only provided by chrome

can you point to examples, please?
we're using https://github.com/mozilla/webextension-polyfill, which should take care of most APIs, but if there's anything missing I'd need to check

**Comment by gabrielpoca** [comment]
I'll add it to my task list. It should be straightforward to do

**Comment by xphoniex** [comment]
> 
> can you point to examples, please? we're using https://github.com/mozilla/webextension-polyfill, which should take care of most APIs, but if there's anything missing I'd need to check

e.g. `chrome.storage` [here](https://github.com/iron-wallet/iron/blob/main/extension/options/index.ts#L18)

**Comment by naps62** [comment]
ah. you're right. I added that page after the initial development of the extension, and apparently forgot about the polyfill at that point. thanks for pointing it out!

**Comment by xphoniex** [comment]
I quickly checked with other extensions and they seem to be using:

```json
  "background": {
    "persistent": true,
    "scripts": ["background.js"]
  }
```

I guess you can make chrome not happy, and it'd still work. Firefox on the other hand.

**Comment by naps62** [comment]
@xphoniex #231 should fix this (tested locally already, just had to tweak the release process).
it's a bit hacky because parcel (our extension builder) seems to not support this currently, but appears to get the job done

I'm aiming to get a new release with this by end of day or tomorrow

**Comment by xphoniex** [comment]
Nice work @naps62 , it's working.

- I can only build it with `yarn release`. I'm not entirely familiar with `yarn` but isn't `yarn build:release` also supposed to work, or is that internal? Getting:
```
yarn run v1.22.19
$ yarn build:release:chrome && yarn build:release:firefox
error Command "build:release:chrome" not found.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
- the created `extension-untagged-firefox.zip` has a folder inside it, which makes it impossible for firefox to directly load it, can be fixed by eliminating the folder.

**Comment by naps62** [comment]
@xphoniex thanks for the feedback. had a couple of small issues with the previous PR apparently. `yarn build:release` was an old command, meant to be deleted. And the extra directory in the zip was also an oversight

however, when trying to install through the zip after fixing it, I'm still unable to on firefox, because it's unverified. from a quick research, seems like firefox removed this ability altogether a few years ago.
so maybe this will only work properly once I release it to the respective stores (which I'll prioritize, since it makes it much harder to use on firefox)

**Comment by xphoniex** [comment]
> however, when trying to install through the zip after fixing it, I'm still unable to on firefox, because it's unverified. from a quick research, seems like firefox removed this ability altogether a few years ago.

works fine for me, are you loading it via **about:debugging#/runtime/this-firefox** ?

**Comment by naps62** [comment]
no. it works through there (it's how I first tested it), but not via `about:plugins`

when loaded through your method it doesn't persist after restart, does it?

**Comment by xphoniex** [comment]
I see. Yeah, I think with `about:debugging` it has to be re-loaded after each restart.

**Comment by naps62** [comment]
no worries. one more reason to release to the proper stores as soon as possible. it also simplifies the release process, since people will no longer have to manually update the extension

**Comment by xphoniex** [comment]
I got a new message when I was loading the extension today (ff updated itself):


![Screenshot from 2023-06-27 14-27-09](https://github.com/iron-wallet/iron/assets/14107758/37f01eb5-85ae-4dfa-8c16-c7cdf2b196d0)

> Reading manifest: Warning processing options_ui.browser_style: "browser_style:true" has been deprecated in Manifest Version 3 and will be unsupported in the near future. While "options_ui.browser_style" was not explicitly specified in manifest.json, its default value was true. Its default will change to false in Manifest Version 3 starting from Firefox 115.

---

Another issue I'm encountering is, if I'm logged in a dapp, on next refresh, it won't work. Sometimes I have to refresh a few times for it to reconnect to tauri again.

I haven't tested on Chrome yet, and not sure if this is only a Firefox thing. Any similar experince?

**Comment by naps62** [comment]
The recommended step on that `browser_style` warning seems to be to remove the key which we don't have in the first place, so it's a bit confusing. I'll try to build with `false` and see if any UI changes. if not, should be safe to ignore

the need to refresh is something other people (at least @davidesilva I think) have also noticed randomly, but I haven't been able to reproduce properly yet
nevertheless, seems like a general issue, not a firefox one. I'll open a ticket and will try to investigate further.
My guess is it's something to do with the websocket connection/retry logic

**Comment by naps62** [comment]
Firefox support has been done for a while. just publishing to the extension store is proving to be a bit of a pain. that's being tracked in #383 now
