### ISSUE TITLE
use tokenlists.org for icon/address verification

### ISSUE THREAD

**Issue by naps62** [iron-wallet/iron#283]
We want to build (at compile-time) a token list for multiple chains
We can fetch them from tokenlists.org (or from the lists they refer to, actually)

we should construct our own erc20s.json, grouped by chain_id, and including things like name, symbol, decimals, and other details (probably follow the same schema listed on tokenlists.org

## Random details:

- probably build this under a `crate/tokenlist/` crate
- create a `build.rs` script that should download one or more of those lists
- parse each list to our own wanted format, e.g.:

```
{
  chain_id: {
    "0x....": {
      "name": "USDC"
    },
    "0x....": {
      "name": "DAI"
    },
    ...
  }
}
```

For now I'd argue only chain_id, address and name are needed. In the future, we may want to add other fields (price oracle address, coingecko ID, bridging information, but for now this should suffice

**Comment by oboutarf** [comment]
Hello i would like to be assigned on this issue!

**Comment by naps62** [comment]
Go ahead @oboutarf ! thank you

**Comment by naps62** [comment]
@oboutarf any updates?
