### ISSUE TITLE
Updating wallet settings does not refresh the initial state

### ISSUE THREAD

**Issue by naps62** [iron-wallet/iron#294]
To reproduce:
1. Go to the test mnemonic settings
2. Toggle "is Dev Account"
3. Save
4. Toggle "is Dev Account" again
5. the form is now in a state where you can't save, because it matches the initial state, even though it was changed in be tween

expected:
the second save should be possible again

Also, arguably after saving we should maybe close the accordion automatically anyway

**Comment by 0xdorifto** [comment]
Hey guys, can I take this issue?

**Comment by naps62** [comment]
Fixed in #337
