### ISSUE TITLE
enable eslint's no-confusing-void-expression

### ISSUE THREAD

**Issue by naps62** [iron-wallet/iron#324]
Nice, we should enable that. For the sake of this change, if having here void doesn't require the `() => { foo(); }` on the parent, I think it's ok, if not, I still think it's probably better to use the unknown.

_Originally posted by @gabrielpoca in https://github.com/iron-wallet/iron/pull/315#discussion_r1285590577_

**Comment by sumanthsumu1418** [comment]
happy to take this one : )

**Comment by naps62** [comment]
@sumanthsumu1418 are you still taking this one? :)

**Comment by Hari-Bombon** [comment]
@naps62 I will take this one
