### ISSUE TITLE
Dark mode selector not working

### ISSUE THREAD

**Issue by 0xdorifto** [iron-wallet/iron#362]
[darkmode-2023-08-30_11.30.35.webm](https://github.com/iron-wallet/iron/assets/57015299/b3af9c73-3ad5-4c5f-a7b2-66cc99b7d087)

It is not possible to get out of the automatic setting.

**Comment by naps62** [comment]
hmm. it seems the setting is working, but the theme stopped reloading after saving settings.

if you right-click & reload, or if you do it via `Ctrl + K`, it works.
So it's still a bug, but just scoped to the settings form
