### ISSUE TITLE
Frontend allowing invalid mnemonic

### ISSUE THREAD

**Issue by 0xdorifto** [iron-wallet/iron#364]
Frontend is allowing invalid mnemonic phrases which is breaking the app:

[1-2023-09-01_15.37.54.webm](https://github.com/iron-wallet/iron/assets/57015299/6953ad76-a4a9-4195-81bc-07100dafcc46)

**Comment by naps62** [comment]
hmm, I thought I had fixed this a while ago, but maybe I'm misremembering. thanks for reporting

**Comment by 0xdorifto** [comment]
I can take this one.

**Comment by naps62** [comment]
this was fixed in #374
