### ISSUE TITLE
Use zxcvbn for password strength estimation

### ISSUE THREAD

**Issue by gabrielpoca** [iron-wallet/iron#366]
The current password strength estimation only looks for the length of the password and forces the existence of a special character. [zxcvbn](https://dropbox.tech/security/zxcvbn-realistic-password-strength-estimation) is used by Bitwarden and allows us to be more flexible and informative at the same time. Having a special character is not mandatory to have a strong password, and there are other things to consider.

**Comment by gabrielpoca** [comment]
@naps62 looks good?

**Comment by naps62** [comment]
yes 👍🏼
