### ISSUE TITLE
Move mnemonic validation to backend

### ISSUE THREAD

**Issue by naps62** [iron-wallet/iron#378]
#374 introduced a useful validation of the mnemonic against the bip39 dictionary. But it did so by introducing a new JS dependency.

Since on the Rust side we already heavily use ethers-rs, and since we prefer to keep all business logic there, it would make sense to move the check to a rust function, exposed through the usual communication API (tauri command, or HTTP API if that's already available by the time we pick this up)

this can be done by adding a new `iron_wallets::utils::validate_menmonic`, and exposing it via the commands / REST API

**Comment by MavericksFive** [comment]
Hello, I can take this one!

**Comment by naps62** [comment]
@MavericksFive awesome! let me know if you need assistance
