### ISSUE TITLE
Consider replacing ethers with viem

### ISSUE THREAD

**Issue by naps62** [iron-wallet/iron#45]
This is a recent library. maybe worth exploring it here
https://twitter.com/wagmi_sh/status/1632814443972395010

**Comment by naps62** [comment]
FYI, this has been reverted, but I'm not gonna re-open the issue, since this won't be possible in the foreseeable future.

Tauri relies on system webviews, which run specific JS targets (`es2021` I believe) which is incompatible with viem

**Comment by jxom** [comment]
Out of curiosity, what features are missing in webviews that cannot be polyfilled? BigInts?

**Comment by naps62** [comment]
@jxom to be fair, I didn't look into whether polyfills were an option or not (I figured throwing more unknowns into it would only cause further issues short-term)
but yes, it was about bigints. you can see the build logs here: https://github.com/iron-wallet/iron/actions/runs/4939277916/jobs/8829875517

**Comment by jxom** [comment]
Ah right. That looks like a Vite build error which you can fix by setting the target in Vite to ES2021. Maybe that would fix it.

**Comment by naps62** [comment]
I couldn't find clear answers about whether that was a good idea or not (example: https://github.com/tauri-apps/tauri-docs/issues/440)

the main difficulty here is that this will run on system's webviews. the safari version running on mac OS depends on the OS's version. I use linux myself, which makes it even harder to verify.

with that said, I'll probably get back to this once I have more time. I guess it was premature to say it "won't be possible in the foresseable future", so maybe after ETHGlobal Lisbon I can give a go at this again
