### ISSUE TITLE
Extension build step is broken on MacOS

### ISSUE THREAD

**Issue by DavideSilva** [iron-wallet/iron#453]
Due to the differences between the behaviour of the `sed` command in Linux and MacOS, the current build script is broken on MacOS devices that use the default `sed` command

```bash
sed: 1: "./dist/chrome/manifest. ...": invalid command code .
error Command failed with exit code 1.
```

One possible fix that works for MacOS is to add one extra argument to the `sed` command in `build.sh` that replaces the version placeholder with the actual value, after the `-i` flag. Another change needed to make this work, is to replace the single quotes around the substitution with double quotes in order for string interpolation to work correctly

Changing this

```bash
sed -i 's/%VERSION%/'$version'/g' $DIST_DIR/manifest.json
```

with this

```bash
sed -i "" "s/%VERSION%/$version/g" $DIST_DIR/manifest.json
```

~Testing is needed to see if the proposed solution works in Linux~
It doesn't work with Linux, more robust solution would probably be detecting the OS and changing the args of `sed` accordingly

**Comment by naps62** [comment]
Fixed in #454
