### ISSUE TITLE
Browser wallet option is not appearing on Firefox

### ISSUE THREAD

**Issue by DavideSilva** [iron-wallet/iron#547]
With the Iron Wallet extension installed on Firefox, it should appear an option to connect with a browser wallet and nothing is showing

<img width="812" alt="image" src="https://github.com/iron-wallet/iron/assets/2940022/a4b0a278-f91d-4b85-ba8c-e8f6db2f97e3">

**Comment by naps62** [comment]
@DavideSilva after #600 I was able to get this working on firefox. I also updated web3-demo, so not sure if that was also related

let me know if the issue persists for you, but closing in the meantime
