### ISSUE TITLE
Import by private key

### ISSUE THREAD

**Issue by nebolax** [iron-wallet/iron#564]
Hey guys, how can I import a wallet by its private key?

**Comment by naps62** [comment]
@nebolax hey there.
currently we don't have that ability (purely because the need never came up), but should be able to easily add that.

In the meantime, if needed, I believe you can convert raw private keys to json keystore files (which we do support)

**Comment by nebolax** [comment]
Thanks!

> In the meantime, if needed, I believe you can convert raw private keys to json keystore files (which we do support)

Never worked with keystore. Could you point me to some resource that will help to quick-start?

**Comment by naps62** [comment]
You can check this code (disclaimer: haven't audited it myself, just found it now): https://github.com/zulhfreelancer/private-key-to-json/blob/master/index.js

not advising to run that directly, but if you check the code, should be easy to see how easy the conversion is (using `ethereumjs-wallet`)

In the meantime, I'll try to get this feature in until tomorrow (should be that easy)

**Comment by nebolax** [comment]
Wow, thank you!!

**Comment by naps62** [comment]
@nebolax first draft at #566 
seems to be working, but it's late night already, so I'll refrain from merging until tomorrow
